### PR TITLE
Magazine Summary Block

### LINKED ISSUE #10: Magazine: Header Navigation: Issue summary
A huge card is shown with the current issue. 

Create summary document for each issue? Or create a metadata table in each issue, that is then pulled into a JSON table. 

Screenshot 2023-07-31 at 10 59 54

### PR DESCRIPTION
**Pull request by rrusher**
Please always provide the [GitHub issue(s)](../issues) your PR is for, as well as test URLs where your change can be observed (before and after):

Fix #10 

Test URLs:
- Before: https://main--24life--hlxsites.hlx.page/drafts/rrusher/magazines/volume-5-issue-12
- After: https://magazine-summary--24life--hlxsites.hlx.live/drafts/rrusher/magazines/volume-5-issue-12

### CODE REVIEW

**Comment by synox** [comment]
pulling from main might help

**Comment by rrusher** [comment]
LHS is fine. The performance page doesn't feel the same way.
Screenshot 2023-09-11 at 4 32 25 PM

**Comment by synox** [comment]
are you saying the score is good, but the actual experience is not fast?

**Review by synox — APPROVED** [review]

**Comment by rrusher** [comment]
@synox No. It's primarily not liking the webfonts and the youtube js. Neither of which have to do with the magazine-summary block.
Screenshot 2023-09-12 at 1 05 42 PM

**Comment by synox** [comment]
ok. Both have an open github issue, so feel free to merge.

**Pull request merged**
